server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  datasource:
    url: jdbc:mysql://localhost:3306/petgo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: nvna2705@gmail.com
    password: ylrr ckeb pbky qspg

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  homepage:
    featured-limit: 3
    nearby-limit: 6
    review-limit: 6
    membership-limit: 3
  providers:
    slot-lookahead-days: 7
    card-slot-limit: 3
    detail-slot-limit: 6
    detail-review-limit: 8

  pets:
    max-photo-limit: 5

  bookings:
    timezone: Asia/Ho_Chi_Minh

  booking-management:
    reschedule-lookahead-days: 14


  auth:
    access-token-expiration-minutes: 120
    refresh-token-expiration-days: 30
    issuer: petgo-backend
    jwt-secret: change-this-secret-key-change-this-secret-key-2026

  upload:
    root-dir: uploads
    pet-avatar-dir: uploads/pets
    pet-avatar-public-path: /uploads/pets

payos:
  client-id: e2918732-3fa1-4d7e-8be9-a4e3b42eb6a4
  api-key: 556763fe-64ba-4b75-aa80-904aee2b396e
  checksum-key: e5607adc68354292c0e7e4bd79ea9e9e1c29c8fb4160def81921582743861d21
  return-url: ${PAYOS_RETURN_URL:http://localhost:5173/payment/success}
  cancel-url: ${PAYOS_CANCEL_URL:http://localhost:5173/payment/cancel}

cloudinary:
  cloud-name: dxaok6qzg
  api-key: 754418163343834
  api-secret: QmNTv-DNsMrC6D6NKmXVse_4i04