server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petgo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

# Custom Properties
jwt:
  signerKey: "PetGoSecretKeyForNghia2026SecureProjectApplication"
  valid-duration: 3600 # đơn vị giây (1 giờ)
  refreshable-duration: 86400 # đơn vị giây (24 giờ)

# Hoặc giữ nguyên petgo nếu bạn muốn dùng cả hai
petgo:
  app:
    jwtSecret: PetGoSecretKeyForNghia2026SecureProjectApplication
    jwtExpirationMs: 86400000